# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 751, 511))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_table = QtWidgets.QTableWidget(self.layoutWidget)
        self.main_table.setObjectName("main_table")
        self.main_table.setColumnCount(3)
        self.main_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.main_table)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_network_activity = QtWidgets.QLabel(self.layoutWidget)
        self.label_network_activity.setMinimumSize(QtCore.QSize(0, 100))
        self.label_network_activity.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_network_activity.setAutoFillBackground(True)
        self.label_network_activity.setText("")
        self.label_network_activity.setObjectName("label_network_activity")
        self.verticalLayout.addWidget(self.label_network_activity)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_start_scan = QtWidgets.QPushButton(self.layoutWidget)
        self.button_start_scan.setObjectName("button_start_scan")
        self.horizontalLayout.addWidget(self.button_start_scan)
        self.button_stop_scan = QtWidgets.QPushButton(self.layoutWidget)
        self.button_stop_scan.setObjectName("button_stop_scan")
        self.horizontalLayout.addWidget(self.button_stop_scan)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.main_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "pid"))
        item = self.main_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "exe-path"))
        item = self.main_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "network activity"))
        self.label.setText(_translate("MainWindow", "Last network activity:"))
        self.button_start_scan.setText(_translate("MainWindow", "Start scan"))
        self.button_stop_scan.setText(_translate("MainWindow", "Stop scan"))
