# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_table = QtWidgets.QTableWidget(self.centralwidget)
        self.main_table.setGeometry(QtCore.QRect(90, 90, 256, 192))
        self.main_table.setObjectName("main_table")
        self.main_table.setColumnCount(2)
        self.main_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(1, item)
        self.button_start_scan = QtWidgets.QPushButton(self.centralwidget)
        self.button_start_scan.setGeometry(QtCore.QRect(110, 320, 80, 24))
        self.button_start_scan.setObjectName("button_start_scan")
        self.button_stop_scan = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop_scan.setGeometry(QtCore.QRect(230, 330, 80, 24))
        self.button_stop_scan.setObjectName("button_stop_scan")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.main_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "pid"))
        item = self.main_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "exe-path"))
        self.button_start_scan.setText(_translate("MainWindow", "Start scan"))
        self.button_stop_scan.setText(_translate("MainWindow", "Stop scan"))
